default: &default
  roles:
    mentor: 0
    naitei: 1
    supervisor: 2
  username_max_length_100: 100

  priorities:
    low: 0
    medium: 1
    high: 2
    urgent: 3

  task_roles:
    - creator
    - assignee

  status:
    pending: 0
    in_progress: 1
    completed: 2
    expired: 3
  task_title_max_length: 255
  task_participant_roles:
    participant: 0
    creator: 1
  actions:
    create: 0
    update: 1
    delete: 2
  comment_max_length_10_000: 10_000
  category_max_length_255: 255
  tasks_per_page_5: 5
  DATE_FORMAT: "%m-%d-%Y"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
